version: '1'
services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        healthcheck:
            test: rabbitmq-diagnostics check_port_connectivity
            interval: 1s
            timeout: 3s
            retries: 30
        ports:
            - "5672:5672"
            - "15672:15672"
    
    profileservice:
        image: profile-service
        build:
            context: .
            dockerfile: ProfileService/Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            rabbitmq:
                condition: service_healthy

    tweetservice:
        image: tweet-service
        build:
            context: .
            dockerfile: TweetService/Dockerfile
        ports:
        - "8081:8081"
        depends_on:
            rabbitmq:
                condition: service_healthy
    