using Microsoft.EntityFrameworkCore;
using SharedMessages;
using System.Collections.Generic;
using System.Linq;

namespace TweetService.Database
{


    public class Database
    {
        public class TweetContext : DbContext
        {

            // Constructor
            public TweetContext(DbContextOptions<TweetContext> options) : base(options)
            {
                // Seed the database if it's empty
                if (!Tweets.Any())
                {
                    SeedData();
                }
            }
            

            // Database Tweet sets
            public DbSet<Tweet> Tweets { get; set; }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<Tweet>()
                    .HasKey(t => t.Id); // Specifies that the Id property is the primary key

                modelBuilder.Entity<Tweet>()
                    .Property(t => t.Id)
                    .ValueGeneratedOnAdd(); // Specifies that the Id property is auto-generated by the database

                base.OnModelCreating(modelBuilder);
            }


            private void SeedData()
{
    var tweets = new List<Tweet>
    {
        new Tweet { Body = "This is a sample tweet.", UserID = 1 },
        new Tweet { Body = "Another sample tweet here.", UserID = 2 },
        new Tweet { Body = "Yet another sample tweet.", UserID = 1 },
        new Tweet { Body = "Sample tweet number four.", UserID = 3 },
        new Tweet { Body = "Fifth sample tweet incoming.", UserID = 2 },
        new Tweet { Body = "Adding more seed data.", UserID = 1 },
        new Tweet { Body = "Yet another tweet for testing.", UserID = 2 },
        new Tweet { Body = "Hello, world!", UserID = 3 },
        new Tweet { Body = "Testing the seeding mechanism.", UserID = 1 },
        new Tweet { Body = "Yet another tweet.", UserID = 2 },
        new Tweet { Body = "Random tweet for testing purposes.", UserID = 3 },
        new Tweet { Body = "A tweet about something.", UserID = 1 },
        new Tweet { Body = "Tweeting all day long.", UserID = 2 },
        new Tweet { Body = "Tweeting is fun!", UserID = 3 },
        new Tweet { Body = "Testing tweet number 15.", UserID = 1 },
        new Tweet { Body = "Yet another tweet for testing purposes.", UserID = 2 },
        new Tweet { Body = "Hello from the tweet world.", UserID = 3 },
        new Tweet { Body = "Tweeting for the sake of tweeting.", UserID = 1 },
        new Tweet { Body = "This is tweet number 20.", UserID = 2 },
        new Tweet { Body = "Tweeting non-stop.", UserID = 3 },
        new Tweet { Body = "Testing tweet number 21.", UserID = 1 },
        new Tweet { Body = "Yet another tweet for testing purposes.", UserID = 2 },
        new Tweet { Body = "Hello from the tweet world.", UserID = 3 },
        new Tweet { Body = "Tweeting for the sake of tweeting.", UserID = 1 },
        new Tweet { Body = "This is tweet number 25.", UserID = 2 },
        new Tweet { Body = "Tweeting non-stop.", UserID = 3 },
        new Tweet { Body = "Testing tweet number 26.", UserID = 1 },
        new Tweet { Body = "Yet another tweet for testing purposes.", UserID = 2 },
        new Tweet { Body = "Hello from the tweet world.", UserID = 3 },
        new Tweet { Body = "Tweeting for the sake of tweeting.", UserID = 1 },
        new Tweet { Body = "This is tweet number 30.", UserID = 2 },
        new Tweet { Body = "Tweeting non-stop.", UserID = 3 },
        new Tweet { Body = "Testing tweet number 31.", UserID = 1 },
        new Tweet { Body = "Yet another tweet for testing purposes.", UserID = 2 },
        new Tweet { Body = "Hello from the tweet world.", UserID = 3 },
        new Tweet { Body = "Tweeting for the sake of tweeting.", UserID = 1 },
        new Tweet { Body = "This is tweet number 35.", UserID = 2 },
        new Tweet { Body = "Tweeting non-stop.", UserID = 3 },
        new Tweet { Body = "Testing tweet number 36.", UserID = 1 },
        new Tweet { Body = "Yet another tweet for testing purposes.", UserID = 2 },
        new Tweet { Body = "Hello from the tweet world.", UserID = 3 },
        new Tweet { Body = "Tweeting for the sake of tweeting.", UserID = 1 },
        new Tweet { Body = "This is tweet number 40.", UserID = 2 },
        new Tweet { Body = "Tweeting non-stop.", UserID = 3 },
        new Tweet { Body = "Testing tweet number 41.", UserID = 1 },
        new Tweet { Body = "Yet another tweet for testing purposes.", UserID = 2 },
        new Tweet { Body = "Hello from the tweet world.", UserID = 3 },
        new Tweet { Body = "Tweeting for the sake of tweeting.", UserID = 1 },
        new Tweet { Body = "This is tweet number 45.", UserID = 2 },
        new Tweet { Body = "Tweeting non-stop.", UserID = 3 },
        new Tweet { Body = "Testing tweet number 46.", UserID = 1 },
        new Tweet { Body = "Yet another tweet for testing purposes.", UserID = 2 },
        new Tweet { Body = "Hello from the tweet world.", UserID = 3 },
        new Tweet { Body = "Tweeting for the sake of tweeting.", UserID = 1 },
        new Tweet { Body = "This is tweet number 50.", UserID = 2 },
        new Tweet { Body = "Tweeting non-stop.", UserID = 3 },
        new Tweet { Body = "Tweet number 51.", UserID = 1 },
        new Tweet { Body = "Tweet number 52.", UserID = 2 },
        new Tweet { Body = "Tweet number 53.", UserID = 3 },
        new Tweet { Body = "Tweet number 54.", UserID = 1 },
        new Tweet { Body = "Tweet number 55.", UserID = 2 },
        new Tweet { Body = "Tweet number 56.", UserID = 3 },
        new Tweet { Body = "Tweet number 57.", UserID = 1 },
        new Tweet { Body = "Tweet number 58.", UserID = 2 },
        new Tweet { Body = "Tweet number 59.", UserID = 3 },
        new Tweet { Body = "Tweet number 60.", UserID = 1 },
        new Tweet { Body = "Tweet number 61.", UserID = 2 },
        new Tweet { Body = "Tweet number 62.", UserID = 3 },
        new Tweet { Body = "Tweet number 63.", UserID = 1 },
        new Tweet { Body = "Tweet number 64.", UserID = 2 },
        new Tweet { Body = "Tweet number 65.", UserID = 3 },
        new Tweet { Body = "Tweet number 66.", UserID = 1 },
        new Tweet { Body = "Tweet number 67.", UserID = 2 },
        new Tweet { Body = "Tweet number 68.", UserID = 3 },
        new Tweet { Body = "Tweet number 69.", UserID = 1 },
        new Tweet { Body = "Tweet number 70.", UserID = 2 },
        new Tweet { Body = "Tweet number 71.", UserID = 3 },
        new Tweet { Body = "Tweet number 72.", UserID = 1 },
        new Tweet { Body = "Tweet number 73.", UserID = 2 },
        new Tweet { Body = "Tweet number 74.", UserID = 3 },
        new Tweet { Body = "Tweet number 75.", UserID = 1 },
        new Tweet { Body = "Tweet number 76.", UserID = 2 },
        new Tweet { Body = "Tweet number 77.", UserID = 3 },
        new Tweet { Body = "Tweet number 78.", UserID = 1 },
        new Tweet { Body = "Tweet number 79.", UserID = 2 },
        new Tweet { Body = "Tweet number 80.", UserID = 3 },
        new Tweet { Body = "Tweet number 81.", UserID = 1 },
        new Tweet { Body = "Tweet number 82.", UserID = 2 },
        new Tweet { Body = "Tweet number 83.", UserID = 3 },
        new Tweet { Body = "Tweet number 84.", UserID = 1 },
        new Tweet { Body = "Tweet number 85.", UserID = 2 },
        new Tweet { Body = "Tweet number 86.", UserID = 3 },
        new Tweet { Body = "Tweet number 87.", UserID = 1 },
        new Tweet { Body = "Tweet number 88.", UserID = 2 },
        new Tweet { Body = "Tweet number 89.", UserID = 3 },
        new Tweet { Body = "Tweet number 90.", UserID = 1 },
        new Tweet { Body = "Tweet number 91.", UserID = 2 },
        new Tweet { Body = "Tweet number 92.", UserID = 3 },
        new Tweet { Body = "Tweet number 93.", UserID = 1 },
        new Tweet { Body = "Tweet number 94.", UserID = 2 },
        new Tweet { Body = "Tweet number 95.", UserID = 3 },
        new Tweet { Body = "Tweet number 96.", UserID = 1 },
        new Tweet { Body = "Tweet number 97.", UserID = 2 },
        new Tweet { Body = "Tweet number 98.", UserID = 3 },
        new Tweet { Body = "Tweet number 99.", UserID = 1 },
        new Tweet { Body = "Tweet number 100.", UserID = 2 },
    };

    Tweets.AddRange(tweets);
    SaveChanges();
}


            // Adds a tweet to the database
            public int AddTweet(Tweet tweet)
            {
                // Adds the tweet to the database
                Tweets.Add(tweet);

                // Saves the changes to the database
                SaveChanges();

                // Returns the id of the tweet if tweet is added
                return tweet.Id;
            }

            // Gets all tweets from the database for a specific user
            public List<Tweet> GetAllTweets(int userId)
            {
                return Tweets.Where(tweet => tweet.UserID == userId).ToList();
            }

            // Gets all tweets from the database for a specific user within a specified ID range
            public List<Tweet> GetNext100Tweets(int userId, int startId)
            {
                // Returns the next 100 tweets after the startId
                return Tweets
                    .Where(tweet => tweet.UserID == userId && tweet.Id < startId)
                    .OrderByDescending(tweet => tweet.Id) // Ensure tweets are ordered by ID in descending order (newest first)
                    .Take(100) // Take the next 100 tweets after the startId
                    .ToList(); //convert to list
            }
        }
    }
}
